# roles/post_migration/handlers/main.yml
---
- name: Display cluster operators status
  ansible.builtin.command: oc get co
  changed_when: false

- name: Display cluster operators status
  ansible.builtin.command: oc get co
  changed_when: false
