---
- name: Check if oc client is installed and binary exists
  network.offline_migration_sdn_to_ovnk.check_oc_client:
  register: oc_check_result

- name: Display oc client version
  ansible.builtin.debug:
    msg: "OpenShift client version: {{ oc_check_result.version }}"
  when: oc_check_result.version is defined

- name: Fail if oc binary or client is not installed or functional
  ansible.builtin.fail:
    msg: "{{ oc_check_result.msg }}"
  when: not oc_check_result.version

- name: Check if KUBECONFIG is set and file exists
  network.offline_migration_sdn_to_ovnk.check_kubeconfig:
  register: kubeconfig_result

- name: Show the KUBECONFIG path
  ansible.builtin.debug:
    msg: "KUBECONFIG file found at: {{ kubeconfig_result.kubeconfig_path }}"
  when: not kubeconfig_result.failed

- name: Fail if KUBECONFIG is not set or file does not exist
  ansible.builtin.fail:
    msg: "{{ kubeconfig_result.msg }}"
  when: kubeconfig_result.failed

- name: Check if the current user is 'system:admin' or a user with cluster admin rights using custom module
  network.offline_migration_sdn_to_ovnk.check_whoami:
  register: oc_whoami_result

- name: Show result of oc whoami check
  ansible.builtin.debug:
    msg: "The output of `oc whoami`: {{ oc_whoami_result.message }}"
  when: not oc_whoami_result.failed

- name: Fail if `oc whoami` is not 'system:admin' or does not have cluster admin rights.
  ansible.builtin.fail:
    msg: "{{ oc_whoami_result.msg }}"
  when: oc_whoami_result.failed
