---
galaxy_info:
  role_name: post_migration
  author: Miheer Salunke (@miheer)
  description: Offline migration helper role to perform post migration checks in the cluster.
  license: Apache-2.0
  min_ansible_version: 2.15.0
