---
- name: End-to-End Tests for `clean_migration_field` module
  hosts: localhost
  gather_facts: false
  vars:
    clean_migration_timeout: 60 # Lower timeout for testing
  tasks:
    - name: Run `clean_migration_field` module
      network.offline_migration_sdn_to_ovnk.clean_migration_field:
        timeout: "{{ clean_migration_timeout }}"
      register: clean_migration_result

    - name: Debug output of `clean_migration_field`
      ansible.builtin.debug:
        var: clean_migration_result

    - name: Assert success when migration field is cleared
      ansible.builtin.assert:
        that:
          - "'Migration field cleared.' in clean_migration_result.msg"
        fail_msg: "Module should have cleared the migration field but failed!"
      when: not clean_migration_result.failed

    - name: Assert failure when timeout occurs
      ansible.builtin.assert:
        that:
          - "'Timeout waiting for migration field to be cleared.' in clean_migration_result.msg"
        fail_msg: "Timeout behavior is not working as expected!"
      when: clean_migration_result.failed and 'Timeout' in clean_migration_result.msg

    - name: Fail if the module fails unexpectedly
      ansible.builtin.fail:
        msg: "Module failed unexpectedly: {{ clean_migration_result.msg }}"
      when: clean_migration_result.failed and "Timeout waiting for migration field" not in clean_migration_result.msg
