---
- name: E2E Test - Verify KUBECONFIG existence
  hosts: localhost
  gather_facts: false
  collections:
    - network.offline_migration_sdn_to_ovnk
  tasks:
    - name: Execute custom module to check KUBECONFIG
      check_kubeconfig:
      register: kubeconfig_result

    - name: Debug Output
      ansible.builtin.debug:
        msg: "{{ kubeconfig_result }}"

    - name: Assert KUBECONFIG exists
      ansible.builtin.assert:
        that:
          - kubeconfig_result.kubeconfig_path is defined
          - kubeconfig_result.kubeconfig_path | length > 0
        fail_msg: "❌ KUBECONFIG is missing or invalid!"
        success_msg: "✅ KUBECONFIG is set correctly!"

    - name: Print KUBECONFIG Path
      ansible.builtin.debug:
        msg: "KUBECONFIG Path: {{ kubeconfig_result.kubeconfig_path }}"
      when: not kubeconfig_result.failed
