---
- name: End-to-End Test for wait_for_network_co Module (Real OpenShift)
  hosts: localhost
  gather_facts: false
  vars:
    ovn_co_timeout: 120 # Set a reasonable timeout for the test
  tasks:
    - name: Run wait_for_network_co module (Success scenario)
      network.offline_migration_sdn_to_ovnk.wait_for_network_co:
        timeout: "{{ ovn_co_timeout }}"
      register: result_success

    - name: Debug module output (Success)
      ansible.builtin.debug:
        var: result_success

    - name: Assert success scenario
      ansible.builtin.assert:
        that:
          - result_success is success
          - '"Network Cluster Operator is in PROGRESSING=True state." in result_success.msg'
      when: result_success is success

    - name: Run wait_for_network_co module (Failure due to timeout)
      network.offline_migration_sdn_to_ovnk.wait_for_network_co:
        timeout: 1 # Force an immediate timeout
      register: result_timeout
      ignore_errors: true

    - name: Debug module output (Timeout Failure)
      ansible.builtin.debug:
        var: result_timeout

    - name: Assert failure due to timeout
      ansible.builtin.assert:
        that:
          - result_timeout is failed
          - '"Timeout waiting for Network Cluster Operator to reach PROGRESSING=True." in result_timeout.msg'
      when: result_timeout is failed
